apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: mini-micro-blog
build:
  artifacts:
    - image: fadygamil/posts-svc
      context: posts-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.go'
            dest: .
    - image: fadygamil/comments-svc
      context: comments-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.go'
            dest: .

    - image: fadygamil/eventbus-svc
      context: event-bus-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.go'
            dest: .

manifests:
  rawYaml:
    - infra/k8s/comments-depl.yaml
    - infra/k8s/eventbus-depl.yaml
    # - infra/k8s/ingress-svc.yaml
    - infra/k8s/posts-depl.yaml
